### ISSUE TITLE
Required field omitted from `CreateOne` calls 

### ISSUE THREAD

**Issue by nettrino** [steebchen/prisma-client-go#956] opened 2023-08-31 12:28 UTC
Given the following schema

```prisma
generator client {
  provider = "go run github.com/steebchen/prisma-client-go"
}

// https://www.prisma.io/docs/concepts/components/prisma-schema/data-sources
datasource db {
  provider = "postgresql"
  url      = "<postgres_url>"
}

enum RepositoryHostingPlatform {
  github
  gitlab
  local
}

enum RepositoryVisibilityType {
  public
  private
}

model RepositoryOrganization {
  /// the internal node identifier of the organization of the hosting platform
  /// for github all internal ids correspond to graphql node_ids not db ids
  platformId   String
  platform     RepositoryHostingPlatform
  name         String
  url          String
  memberCount  Int?                      @map("member_count")
  isVerified   Boolean?                  @map("is_verified")
  createdAt    DateTime                  @default(now()) @map("created_at")
  updatedAt    DateTime                  @default(now()) @updatedAt @map("updated_at")
  repositories Repository[]

  @@id(name: "repositoryOrganizationId", [platform, platformId])
  @@map("repository_organizations")
}

enum RepositoryFlavor {
  git
  svn
  cvs
  hg
}

model Repository {
  /// the internal node identifier of the organization of the hosting platform
  platformId String
  platform   RepositoryHostingPlatform
  name       String?
  /// A repository can always just be a local repository without being pushed in any org
  orgId      String?                   @map("org_id")
  org        RepositoryOrganization?   @relation(fields: [platform, orgId], references: [platform, platformId])
  url        String
  isFork     Boolean?                  @map("is_forked")
  createdAt  DateTime                  @default(now()) @map("created_at")
  updatedAt  DateTime                  @default(now()) @updatedAt @map("updated_at")
  visibility RepositoryVisibilityType?
  flavor     RepositoryFlavor          @default(value: git)

  @@id(name: "repositoryId", [platform, platformId])
  @@map("repositories")
}
```
after running `go run github.com/steebchen/prisma-client-go generate` inconsistent types are created for `CreateOne` calls for `Repository` and `RepositoryOrganization`. In particular, `platform` is omitted from `Repository` CreateOne calls:
```golang
func (r repositoryActions) CreateOne(
	_platformID RepositoryWithPrismaPlatformIDSetParam,
	_url RepositoryWithPrismaURLSetParam,

	optional ...RepositorySetParam,
) repositoryCreateOne {
``` 
but is present in `RepositoryOrganization` calls:
```golang
func (r repositoryOrganizationActions) CreateOne(
	_platformID RepositoryOrganizationWithPrismaPlatformIDSetParam,
	_platform RepositoryOrganizationWithPrismaPlatformSetParam,
	_name RepositoryOrganizationWithPrismaNameSetParam,
	_url RepositoryOrganizationWithPrismaURLSetParam,

	optional ...RepositoryOrganizationSetParam,
) repositoryOrganizationCreateOne {
```

**Comment by steebchen** [comment] 2023-08-31 19:35
Thanks for the report. Looks like the issue is having a composite key as a unique index which results in the Go client generating the wrong create fields. Looking into it

**Comment by steebchen** [comment] 2023-08-31 21:25
Potential fix live, try it via `go get github.com/steebchen/prisma-client-go@90bbd6860d248faecf50c907e98cf7aa689dc798`

**Comment by nettrino** [comment] 2023-09-01 06:44
Thank you for the quick turnaround on this!

**Comment by nettrino** [comment] 2023-09-01 10:03
Actually nevermind the panic is due to a [separate bug](https://github.com/steebchen/prisma-client-go/issues/963)

**Comment by steebchen** [comment] 2023-09-01 19:56
So to confirm your @@id primary key issues are fixed on my branch? If yes, I will merge it to main

**Comment by steebchen** [comment] 2023-09-01 19:58
checking `Link` later as well actually. also working on adding a helper method to query for composite id fields (equivalent functions as @@unique fields get)

**Closed** 2023-09-01 20:00 UTC

**Comment by nettrino** [comment] 2023-09-02 06:44
yes fixed - thank you!

**Comment by steebchen** [comment] 2023-09-03 00:33
@nettrino also added tests for Link via https://github.com/steebchen/prisma-client-go/pull/967 – was there anything else around Link not working? I remember you mentioned something
