### ISSUE TITLE
(EDIT: OUDDATED!) P̶r̶i̶s̶m̶a̶ ̶C̶l̶i̶e̶n̶t̶ ̶G̶o̶ ̶w̶i̶l̶l̶ ̶n̶o̶t̶ ̶b̶e̶ ̶O̶f̶f̶i̶c̶i̶a̶l̶l̶y̶ ̶M̶a̶i̶n̶t̶a̶i̶n̶e̶d̶ ̶a̶n̶y̶ ̶m̶o̶r̶e̶

### ISSUE THREAD

**Issue by matthewmueller** [steebchen/prisma-client-go#707] opened 2021-12-21 22:16 UTC
# **EDIT: THIS ISSUE IS OUTDATED!**

**PLEASE SEE --> [Prisma Client Go: Resurrection](https://github.com/steebchen/prisma-client-go/issues/860) <-- FOR AN UP-TO-DATE OVERVIEW.**

----

_original issue (Dec 21, 2021):_

Hey everyone,

After a lot of consideration, we've decided to stop the development on the Go Client. The Go client has unfortunately not seen the growth we were hoping for. To understand this decision a bit better, I'm sharing a chart that shows the number of installs over the last 12 months:

![image](https://user-images.githubusercontent.com/170299/147004541-ad05593e-52de-4950-9453-bfdc6cf82d1a.png)

As you can see, there's been stable adoption, but not much growth. 

This doesn't mean that the Go client isn't useful or that the Go Client is a bad idea. We've just learned that the Go Client won't grow by itself. We would need to invest more resources to reach the kind of adoption we would need to sustain the development. Given our priorities for the next year, the Go Client just didn't make the cut.

I'd like to take a moment to thank @steebchen for his work on the Go client for the last 2 years. He's been working tirelessly on answering questions, fixing bugs and implementing the features you've been asking for. 

I've added an FAQ below, but I'll leave this thread open to answer any additional questions you might have. We're sorry for the inconvenience this may cause you.

### When does the development stop?

We are stopping the development of the Go Client immediately.

### Will critical issues and bugs be fixed?

Unfortunately, we won’t have any resources to fix any outstanding or upcoming issues with the Go Client. Community members are more than welcome to fork the repo and continue the development of the Go Client on their own (as a reference, you can look at the [Python Client](https://github.com/RobertCraigie/prisma-client-py/) which has been developed from scratch by a community member as well). If anyone is interested in that, we are happy to help with the first steps in adopting and distributing. 

### What is going to happen to the repo?

This repository will remain in place as a point of reference.

### Will you change your mind in the future and pick up the development again?

Possibly. As we grow larger and reach more enterprises, the Go ecosystem is likely to become more relevant again. The type of Go Client we offer then may look different than the current one though.

**Comment by shinebayar-g** [comment] 2021-12-22 15:20
Cool, right after I learned about prisma go client. 🙄

**Comment by hi019** [comment] 2021-12-22 15:58
This is super unfortunate, you guys made an amazing ORM :(. Thanks @steebchen for all your work maintaining the client, especially the speedy issue responses and quick fixes

**Comment by bjaanes** [comment] 2021-12-23 11:27
That is unfortunate. But isn't it also a bit premature to make any conclusions on adoption with something that has only been in "Early Access"? The note on those kinds of features are "We don't recommend using Early Access features or products in production."

So for instance I have personally followed the development and wanted to use this when it was ready, but I don't have time to play with it until it is more ready. 

I of course respect your decision on this, but I find the argument a bit weak. I also would not expect to see a lot of growth for something that you can't use for anything real :)

**Comment by yar2001** [comment] 2021-12-25 02:20
Oh No... I've been struggling for a while whether I should migrate to Prima (from gorm). 

Prima really accords with my ideal ORM.  None of the other ORM in Go (as I know)  can construct `Where` clauses with auto completion and provide consistent development experience.

The reason that Prisma haven't seen the growth is probably nobody knows it. If I am a beginner, I will Google it to compare all the ORM. And no results in the first page (for my locale, key word: `go mysql orm` and `go postgres orm`). 
 
![image](https://user-images.githubusercontent.com/20311434/147375763-6effddb1-bc03-465d-b37c-c19a1c9f1087.png)

I found Prima because I use Nest.js too, and I found Prima in [nest.js document](https://docs.nestjs.com/recipes/prisma). I haven't started using it yet (because I use MongoDB for node) but it impressed me a lot. When I use Go for MySQL and Postgres, I am disappointed to find that the popular ORM in Go fail to provide a good experience(compared with TypeScript, the latter provide a really good type system). So I just wonder will some library provide SQL generator just like Prima, and I found that Prima offers it itself! However, when I hesitated whether to migrate to Prima, I found this announcement. 

Anyway, what you guys are doing is awesome, and hopefully more people will get a chance to use it one day.

**Comment by s-takehana** [comment] 2021-12-28 11:45
![えー！_gifmagazine](https://user-images.githubusercontent.com/3423547/147563032-35818b8c-4608-4f4c-90a5-a37bdd69e7b7.gif)

**Comment by Southclaws** [comment] 2021-12-29 08:57
This is really unfortunate to hear, thanks @steebchen for maintaining it and answering all my questions over the years!

I literally just migrated my company's database ops to Prisma, and while Prisma itself is still useful as a schema and migration tool we'll have to consider an alternative.

Which sucks a lot because I've been writing Go for many years and none of the database connectors come anywhere close to Prisma - they're all string based and not type safe.

I may consider helping maintain this as it's so useful and I use it in 3 production applications (2 of which are businesses) 

I am also surprised at the move, but I think this tool really needs more fanfare in the Go community. I attend the London Gophers meetup and this would be a fantastic platform to tell Go engineers about Prisma. I really hope you focus on Go again in future as it's a huge language in the enterprise space and in my experience, often the go-to tool for migrating legacy systems into new world tech - `prisma db pull` is vital for these legacy migrations.

Anyway, thanks for your work! I will poke around the codebase and learn it a bit more.

**Comment by robin-macpherson** [comment] 2021-12-29 11:11
This is really unfortunate and is a bit of a painful reminder of the abandoned Nexus Framework project and the abandoned `nexus-plugin-prisma` package (that one with a new project to rebuild it, but with zero support of the old one in the meantime and putting people who were using it in production in a horrible position for an incredibly long time now). Both of these totally screwed us for lengthy stretches.

I'm not sure if this is being unfair to Prisma or not, but it's starting to feel like there is a bit of a grave yard that we keep arriving at time and time again...

In any case, echoing other comments, thanks so much @steebchen for all of your work on this – I can't imagine how you must be feeling with this news.

**Comment by AmreeshTyagi** [comment] 2021-12-30 01:59
Thanks @steebchen for your great work.
It's a bad news for those who are migrating their tech ecosystem from nodejs-prisma to golang-prisma or planning golang with prisma like me.  :(

**Comment by Southclaws** [comment] 2021-12-30 12:11
From what I've heard from Go developers I know, the reason this project wasn't picked up was because it was branded as "experimental" so you can't really expect real usage at real live company software to use an experimental package.

But from my ~2 years of using it in 4 projects (2 of which were for business - yes, I'm a risk taker!) it didn't seem _that_ unstable and I feel like you could have made the pitch a little less scary to increase usage.

Another thing is just the age old blog posts and videos/screencasts to get people excited - the TypeScript side of Prisma has loads of great marketing efforts. If the same were to be done for Go, believe me it would be huge because Go's database landscape is really really lacking compared to more mature languages like Java, C#, Ruby, etc.

**Comment by paulm17** [comment] 2022-01-01 16:00
Just want to come at this from another angle.  

I tried picking this up myself and kept running into issues.  So went back with plain old database/sql.

I'm practically on the verge of dropping **Prisma entirely**.  Don't get me wrong, I love the typescript version.  But with the last 5 or 6 releases being focused on Mongodb, which frankly is not taken seriously because Postgres with a jsonb column is 100x better.  It's signalling to many, that the desire to be cross compatible rather than shoring up important issues that the community (loudly) has been asking for, is more preferable.

With a barrage of issues that are open, not only affecting me and (probably) other individuals on the same boat after a full year.  My excitement is starting to wane.  I'm well past the point where basic features will suffice and wanting more complex functionality just isn't there, well is frankly disappointing.

Upon hearing these news, well its saddening.  You don't develop a library in the hopes that it will be popular.  With Go, you develop it because you want to be in the Enterprise space.  And that's what you want to signal.

**Comment by TheBeachMaster** [comment] 2022-01-08 13:18
This is horrible, and I just feel like someone has just pulled the rug under my feet... I have 3 production apps running on this client. 

Now I have to spend days migrating 10'000s of LOCs to `ent`.  
<img width="747" alt="Screenshot 2022-01-08 at 16 16 54" src="https://user-images.githubusercontent.com/9129843/148645596-32b60fe8-fe6e-49d7-84cb-e6dbf5321faa.png">


If you label a project as `Early Access` clearly people would hesitate adoption(a few of us took risks to run it on prod so that we can give feedback https://github.com/prisma/prisma-client-go/issues/539 and make the package better).

This is a punch on the face for some of us.

I'd like to thank @steebchen for his patience and swiftness in responding to my queries and issues and the amount of effort he put in to this project. ❤️

**Comment by johnpena** [comment] 2022-01-18 21:25
I find this to be a really strange and anti-strategic decision for the Prisma team to make. 

I thought Prisma's brilliant innovation was that it allowed you to have a single schema (or set of schemas), from which you could:
a. generate clients for every language you use
b. have a multitude of services sharing a single database or a set of databases
c. manage everything through a single interface and tool set (e.g. prisma migrate) 

Such an innovation would solve problems I've had at every company I've ever worked for. Want to have two services written in different languages that use the same database? You can do that. Want to start writing things in language A and then port them to language B? You can do that too. Want to move a use case from service A to service B without having to rewrite everything? Basically zero effort. 

The fact that the Prisma team is moving away from this work tells me they don't understand this enormous problem and the value that they were already providing in solving it. Instead of solving this problem (which is widespread, and for which I don't know of another existing equivalent solution) and leaning into it, the Prisma team seems to just be focusing on being a better node ORM than sequelize or knex or waterline or any of the already pretty good ORMs for node. 

Definitely a head-scratcher.

**Comment by matthewmueller** [comment] 2022-01-20 17:48
Hey @johnpena, thanks for your message, I think your read is correct. 

> Prisma team seems to just be focusing on being a better node ORM than sequelize or knex or waterline

This is definitely our top goal for the next year or so. We want to be the dominate ORM in the Node.js ecosystem. We're not there yet. Reaching this milestone is required for everything else we do. 

> I thought Prisma's brilliant innovation was that it allowed you to have a single schema (or set of schemas)

I totally agree with you. As a Go and TS developer myself, being able to switch between the languages and apply the same concepts with the same schema is hugely useful.

This was seriously a tough call. But it boiled down to:
- We really need to focus on making the TS Client the best it can possibly be
- The Go Client isn't a breakout success and requires effort and resources to make it so (someone mentioned videos, content marketing, etc.)

I'd also say I think we started this effort too early in our journey. After we become the defacto standard in the TS ecosystem, I do see us branching out to other languages again, more deliberately, with more resources. How that shapes up, remains to be seen.

**Comment by Southclaws** [comment] 2022-01-21 11:50
Do you plan to provide resources for community clients in future? I'd love to look into contributing and buiding generators but there seems to be a lack of documentation for the query engine RPCs.

**Comment by stephenafamo** [comment] 2022-01-24 17:53
I would like to recommend [SQLBoiler](https://github.com/volatiletech/sqlboiler) as an alternative.

It generates type-safe models and query builders from your DB schema, and you can confidently regenerate the models whenever your DB schema changes.   
This means you can continue to use Prisma's schema definition to manage your schema and migrations, **and then** generate your models from your updated DB.

Sadly, this does not really help those who are **already** using this client in production, migrating to any other tool would likely be a bit difficult, but for newer codebases, I believe SQLBoiler is a pretty great ORM with a similar philosophy that can fit well with other Prisma tools.

*Disclaimer: I am one of the maintainers of SQLBoiler (although that is a recent development 😅)*

**Comment by jjonsson** [comment] 2022-01-24 19:23
> I would like to recommend [SQLBoiler](https://github.com/volatiletech/sqlboiler) as an alternative.

From SQLBoiler's documentation:

> Table names and column names should use snake_case format.
>  - We require snake_case table names and column names. This is a recommended default in Postgres

This means we would need to change all our names to snake_case to use SQLBoiler, right?

**Comment by stephenafamo** [comment] 2022-01-25 10:35
> This means we would need to change all our names to snake_case to use SQLBoiler, right?

That is pretty old, and this is no longer true. I took some time to check this and it works just fine.

To be clear, postgres makes everything lowercase, so when getting the table names and column names from the DB to generate the schema, **with postgres**, the driver gets everything in lowercase which may cause the model attributes to look weird.  
For example, `Jets.PilotID` will become `models.Jet{Pilotid string}`

**Comment by RobertCraigie** [comment] 2022-01-27 01:11
This is very sad news, the Go Client was instrumental in the creation of my [Python Client](https://github.com/RobertCraigie/prisma-client-py), it probably wouldn't even exist without the Go Client. I'd like to say a massive thank you to @steebchen 💚. I hope Prisma picks this back up in the future.

> @Southclaws Do you plan to provide resources for community clients in future? I'd love to look into contributing and buiding generators but there seems to be a lack of documentation for the query engine RPCs

If anyone is interested in building generators I'd be more than happy to help and answer any questions.

For RPC reference these modules could be useful for anyone wanting to implement it themselves:

Generation RPC loop:
https://github.com/RobertCraigie/prisma-client-py/blob/main/src/prisma/generator/generator.py#L80-L133

RPC interface:
https://github.com/RobertCraigie/prisma-client-py/blob/main/src/prisma/generator/jsonrpc.py

**Comment by Raraku** [comment] 2022-01-28 06:44
I just thought about how convenient it would be to use Prisma for golang and I got excited when I found out there was a client library. This is sad news ... tbh.

**Comment by Southclaws** [comment] 2022-01-31 10:46
Looks like SQLBoiler is the tool to go for. It plays nicely with Prisma's existing schema management.

I was evaluating Ent and sqlc but both are tightly coupled to the schema and migration process. I'd prefer to keep using Prisma's schema and migration tools as they are excellent.

Because SQLBoiler reads from the DB in order to generate code, this makes it possible to work alongside Prisma. I think more tools should be built around this database-first paradigm of generating stuff (like declarative source-of-truth schemas or code) from the database itself!

So, my workflow might look like:

- Edit schema.prisma
- Run `prisma migrate dev --skip-generate` skip generating code
- Run sqlboiler generator from the newly migrated development DB
- Avoid writing dirty non-typesafe awkward SQL string literals for another week 🎉 💯 😁

**Comment by oSethoum** [comment] 2022-02-01 16:30
For those who loved using Prisma Go, I suggest taking a look at the Entgo ORM which is by far the best and the fastest in my opinion at least.

**Comment by dfalgout** [comment] 2022-02-11 05:46
Though I was looking forward to Go support becoming GA, I completely understand and appreciate your decision to keep focused on providing the best experience for TS first.

It is far better to become the de-facto for a narrow market before expanding. I appreciate the work the team at Prisma has done so far on all of their offerings. I am very happy that you have the sense to make these difficult decisions because it means that one day (maybe) we can have this in Go!!

GO TEAM PRISMA!

**Comment by Southclaws** [comment] 2022-03-12 12:28
Playing with Ent as an option, annoyingly it's a full solution (its own schema and migration tooling) so I started a simple converter script: https://github.com/Southclaws/prisment

Feel free to try it out, contribute code, etc.

**Comment by iScorpius** [comment] 2022-03-13 09:04
Prisma is the bestest orm of golang and i've always believed. Just hope prisma for golang will be back in future someday. Thanks to every developer and contributor.

**Comment by Frosty21** [comment] 2022-03-14 14:47
I can understand where @matthewmueller is coming from and I appreciate the clarity and the transparent communication from the Prisma Team. Things come and go, but support with Go will come in time. As @dfalgout said keeping focused on the best for TS first with prisma is the logical decision even though it's a tough decision. 
I can empathize with @robin-macpherson on `nexus-plugin-prisma` support being dropped being similar to this but I think it was necessary and now the community can take it. For me using `nexus-prisma` is really smooth to use once you get past the JSDocs (still need work) but its low priority atm but its TS first so they'll hopefully keep support for that.
Go will come back it's just a matter of time and demand

**Comment by web2033** [comment] 2022-05-02 15:29
Is it still useable? (I see you do some gradual updates)
I'm using both Node.js and Go and would love to see this project afloat...

**Comment by sejr** [comment] 2022-05-07 17:51
Another person here who has been following the development of this for as long as I can remember. Was actually visiting this repository in the hope that it was finally stable.

Prisma was so close to becoming "the" data modeling language across not just my own personal projects, but at places I've worked. With this move, that is no longer feasible. Back to GraphQL and/or protobufs I suppose.

Thanks @steebchen for all of your hard work.

**Comment by Celso-Ricardo** [comment] 2022-05-15 07:27
That's bad. I was starting to be encouraged to learn GoLang when I saw that The Great Prisma ORM had Support for Go. 
Hopefully Things will change in the future. Great Job Guys !

**Comment by denik1981** [comment] 2022-05-16 02:24
I have a web app in TS and prisma and not playing to migrate to Golang, but when it counts to designing the CLI (terminal) I find better options in the Golang ecosystem. I would like to use my already defined prima schema to talk to the DB hence this project was extremely useful. I'm sad.

**Comment by Pherwerz** [comment] 2022-05-18 12:19
what can we do to bring this project back

**Comment by johnoldham33** [comment] 2022-05-19 13:11
I too would like for this to be supported again, prisma seems to be the de-facto ORM for TS/JS and it would be really nice to combine microservices written in go and TS using one schema definition and one client generator, would be incredible. Using sqlboiler for now

**Comment by denik1981** [comment] 2022-05-19 13:29
> s to be the de-facto ORM for TS/JS and it would be really nice to combine microservices written in go and TS using one schema definition and one client generator, would be incredibl

The current pool of ORM clients as alternatives to Prisma is quite low in the Go ecosystem.

**Comment by gurleensethi-docker** [comment] 2022-07-25 22:21
This is unfortunate, I am pretty sure if you release a GA version it soon will become the db package of choice in Go community. 'Early Access' keeps a lot of devs and organizations off from using it.

**Comment by kaykhan** [comment] 2022-08-01 09:36
Used prisma in my node.js/typescript projects, moving to golang project would have liked this. Someone has mentioned ent but i found the introspection tool (entimport) is not as mature as prisma's.

**Comment by gurleensethi-docker** [comment] 2022-08-04 14:54
I would also add that in my recent analysis of past few months, there is slowly a shift happening in the industry where more and more individuals and teams are realizing that `node` is not the way to go for backend applications and considering jumping ship to languages like `Go` and `Rust`. For example, you can see a [recent post from Facebook Engineering](https://engineering.fb.com/2022/07/27/developer-tools/programming-languages-endorsed-for-server-side-use-at-meta/) about adding `Rust` as a supported server side language.

So not only would a `Go` client make sense but a `Rust` client as well.

**Comment by jamesblackjr** [comment] 2022-08-05 04:06
I currently use Prisma for Node projects but now Go has become an important part of our stack, we wanted to use this Prisma client, and maybe we will if it gets enough community support. If I had to choose between keeping Prisma and switching to Go or Rust over Node, certainly I may have to drop Prisma from the stack, which would be unfortunate because I love Prisma!

**Comment by Southclaws** [comment] 2022-08-08 12:49
Ent is almost there with [Versioned Migrations](https://entgo.io/blog/2022/05/09/versioned-migrations-sum-file/) but the DX is still not as good as Prisma was.

**Comment by iansinnott** [comment] 2022-08-08 13:02
Ent is also a very nice project but (to my knowledge) it doesn't have a `db pull` equivalent, which is very helpful for migrating to prisma if you have an existing database.

It would also be great to have a solution that works in both Node and Go (and others, ideally). Take prisma with you to whatever language you use.

That being said, i've had a good experience with ent and it's worth checking out for anyone who's turned off by the unmaintained status of this lib.

**Comment by s-takehana** [comment] 2022-08-09 03:10
@matthewmueller 
Is there any update on this?

**Comment by Southclaws** [comment] 2022-08-13 19:55
> Ent is also a very nice project but (to my knowledge) it doesn't have a `db pull` equivalent, which is very helpful for migrating to prisma if you have an existing database.
> 
> It would also be great to have a solution that works in both Node and Go (and others, ideally). Take prisma with you to whatever language you use.
> 
> That being said, i've had a good experience with ent and it's worth checking out for anyone who's turned off by the unmaintained status of this lib.

They're not as good but there's [primsment](https://github.com/Southclaws/prisment) and [entimport](https://github.com/ariga/entimport)

**Comment by iansinnott** [comment] 2022-08-14 03:43
> They're not as good but there's [primsment](https://github.com/Southclaws/prisment) ...

Thanks @Southclaws. Hadn't seen these. 

I actually started hacking on something similar the other day to do Prisma->Ent conversion. Even if prisma-go was maintained I think this might be preferable in certain cases, such as when you want to ship the whole thing to a user. You can do away with the prisma/engine and associated binary complexity. 

Still hope prisma-go becomes a thing though.

**Comment by johnpena** [comment] 2022-08-14 14:01
For those still looking for an alternative, we moved our production code from prisma-go to sqlboiler. By and large this was a seamless transition (leaving aside of course the fact that we had to rewrite a lot of code.) sqlboiler models are generated from your database schema, so we've continued to use prisma for schema management and migrations. 

One thing I feel the need to mention is that our database read and write speeds have dramatically increased, likely due to removing prisma's serialization/deserialization step.

**Comment by Southclaws** [comment] 2022-08-14 17:27
Honestly, there are so many layers to this problem I'd rather just have a new relational database that doesn't need some 1970s text-based language to transpile to and was code-gen type safe from the start 😂

**Comment by steebchen** [comment] 2022-08-15 20:25
^ this 😂

**Comment by GuilhermeAmado** [comment] 2022-09-20 22:52
> Honestly, there are so many layers to this problem I'd rather just have a new relational database that doesn't need some 1970s text-based language to transpile to and was code-gen type safe from the start 😂

Something like [SurrealDB](https://surrealdb.com/)?

**Comment by Southclaws** [comment] 2022-09-21 08:57
> > Honestly, there are so many layers to this problem I'd rather just have a new relational database that doesn't need some 1970s text-based language to transpile to and was code-gen type safe from the start 😂
> 
> Something like [SurrealDB](https://surrealdb.com/)?

Looks like this still uses an SQL-like query language, unless there's a more low level API hidden in their docs 👀

**Comment by und3fined** [comment] 2022-10-03 03:26
Late 2022, I started use Prima (maybe it's late). I think, no any tools better Prisma. 
Anyway, thank you Prisma team.

**Comment by andyfleming** [comment] 2022-10-15 19:41
Prisma having a first-class go toolset is a valuable proposition for adopters.

It provides a path for scaling projects that start in javascript/typescript but need to scale up parts/all of their API once they have stabilized. Leveraging a second, faster language, like go, gives them that escape hatch.

I hope to see this project picked back up.

**Comment by TheFern2** [comment] 2022-10-16 13:31
This is one of the worse things I've read in a while. Imagine if any inventor based their work on a silly graph, we would still be using candles as opposed to light bulbs. We would still be using horses instead of vehicles.

**Comment by Southclaws** [comment] 2022-10-17 09:40
It's frustrating I know but Prisma is a company with priorities. If they didn't make tough decisions like this, then the brilliant tooling Prisma have built may not exist! So while I think we're all disappointed that support has dropped so early into its lifecycle, we can be understanding that decisions must often be data-driven. I'm hoping Prisma make a return to Go once their business has scaled up a bit more and they have the capacity to commit resources to other markets. 🚀

**Comment by lukasholzer** [comment] 2022-11-20 13:23
I think what's missing in this data chart is the number of developers that don't adopt Prisma because of a lacking go client that is officially supported/maintained

**Comment by AriaFantom** [comment] 2022-11-25 18:58
I hope this project get started officially maintained it will be very easy to convert languages and sync between them

**Comment by sarmad4444** [comment] 2022-12-21 11:29
It's been a whole year and I'm very glad to see the features and adoption prisma(JS) got over this year. There are now thousands of tutorial videos and articles, a well-established community and QAs. I think now (after a complete year), the prisma team should reconsider their decision and continue work on go client. This will be an amazing gift for new year.

**Comment by stephenafamo** [comment] 2023-01-19 10:10
Here to suggest [Bob](https://github.com/stephenafamo/bob) as an alternative.

Bob has a first-class [**Prisma driver**](https://bob.stephenafamo.com/docs/code-generation/prisma) which will use your existing `schema.prisma` file to generate an ORM and Factory.

There is a known issue caused by the prisma CLI not passing `@map` and `@db` attributes on columns. [See Issue 3998](https://github.com/prisma/prisma/issues/3998). However, if the community finds it useful, I plan to support the Prisma schema as closely as possible, writing a custom parser if necessary.

GitHub Link: https://github.com/stephenafamo/bob
Website: https://bob.stephenafamo.com/docs

**Comment by eliliam** [comment] 2023-05-23 00:01
Wow, I am actually shocked that Prisma would drop Go support entirely, right during the biggest growth phase of the entire Prisma project. This is a huge blow to the usability of Prisma in enterprise applications, especially ones that are shifting away from JavaScript due to performance and maintainability issues. Golang has huge adoption in enterprise environments, but is somewhat lacking in personal projects, which I feel is where the Prisma team is looking at specifically in this decision. 

Please reconsider this decision, and at least provide a minimal client for Go, even if it may be somewhat lacking compared to the JS/TS client.

**Comment by bulenttokuzlu** [comment] 2023-05-23 08:38
Well, I am pretty sad to hear that. Golang is for enterprises, not for home developers, looking for fancy interface tools.
We are a company developing services for enterprises, and we use java, go, nodejs, javascript, vuejs, flutter, k8s, etc.... etc.....
Golang is the by far the best utilized, best performing, stingy for resources, container friendly, easy to develop language we are using.

**Comment by merlindru** [comment] 2023-05-28 14:04
Please reconsider this.

On that note, I still see commits by @steebchen keeping things up to date.

Why not make it official? 😉

**Comment by saolof** [comment] 2023-05-30 22:18
I guess this is another case of Go being widely adopted by application authors but not so much by library authors. Both the language and ecosystem have a bias towards YAGNI applications over building libraries.

**Comment by steebchen** [comment] 2023-05-30 23:37
Hello everyone, it's @steebchen, the main maintainer of the Go client.

I've been considering resuming work on the project, especially because of the recent activity. I truly believe that the Go client is a valuable tool that many people would appreciate, as the Go ecosystem currently lacks a robust database client and tooling at this time. Prisma seems to effectively fill this gap.

If anyone is interested in advancing the Go ecosystem by reviving the Go client, ensuring its maintenance, and enhancing it with new features, I would be sincerely grateful if you could consider supporting me [through a sponsorship](https://github.com/sponsors/steebchen). Maintaining and expanding the Go client requires a significant amount of effort. The next big goal would be to release a production-ready version and market it as such.

I have some plans in mind for the Go client, but to dedicate more time to it than just a few hours a month, a sponsorship would be a wonderful option. By choosing a higher sponsorship tier, you would also receive the added benefits of prioritizing your issues as well as personal assistance from me, whether for you individually or for your company. I can provide help with setting it up, as well as consultation on any Go client, database, infrastructure, or CI/CD related matters.

If you're interested in supporting the development of the Go client, please consider [sponsoring me via GitHub sponsors](https://github.com/sponsors/steebchen), or [contact me to discuss](mailto:contact@luca-steeb.com). Your support would be greatly appreciated.

**Comment by vasiliyb** [comment] 2023-06-11 14:58
@steebchen lets remove the [deprecation notice](https://github.com/prisma/prisma-client-go/blob/main/README.md#deprecation-note), love to see the Go client getting attention!

**Comment by steebchen** [comment] 2023-06-14 11:56
The Prisma Client Go repository was transferred to me now (big thank you, @janpio and @prisma!), so it lives at https://github.com/steebchen/prisma-client-go from now on, and is now officially maintained again by me.

**---> Read the full announcement: [Prisma Client Go: Resurrection](https://github.com/steebchen/prisma-client-go/issues/860) <---**

Read the quick start on the new docs page: [Quickstart](https://goprisma.org/docs/getting-started/quickstart)

If you already have a Prisma project, read the [upgrade manual](https://github.com/steebchen/prisma-client-go/issues/857).

I'd also like to thank Alexander Belanger and Bryan Onel at https://www.oneleet.com for being the first bronze sponsor, as they are already using the Go client. If you like these news, let your employer know that the Go client is revived, and if they ask, send them [my sponsor profile](https://github.com/sponsors/steebchen) 😀

See --> https://github.com/steebchen/prisma-client-go/issues/860 for more!

**Closed by steebchen** 2023-06-14 11:56 UTC

**Comment by steebchen** [comment] 2023-06-16 14:15
Thank you @Oneleet, @f-tepel and @osilkin98 for sponsoring! ❤️
