### ISSUE TITLE
ARM / mac M1 support

### ISSUE THREAD

**Issue by stillmatic** [steebchen/prisma-client-go#873] opened 2023-06-16 19:45 UTC
Hello, I'm trying to install the package on M1 Mac and it is failing to do so -- `panic: could not run [generate --schema ../../packages/db/prisma/schema.prisma --verbose]: fork/exec /Users/hua/Library/Caches/prisma/binaries/cli/4.15.0/prisma-cli-darwin-x64: bad CPU type in executable`. It appears that when searching for binary, the package hardcodes x64 https://github.com/steebchen/prisma-client-go/blob/main/binaries/binaries.go#L25. 

The packages are properly built, eg `prisma-cli-4.15.0-darwin-arm64.gz` - I think that we just need to add the architecture (x64 or arm64) as an argument to the URL. 

I'm happy to make a PR for that, I think it should be pretty straightforward.

**Comment by steebchen** [comment] 2023-06-16 19:48
Thanks for reporting, will take a look

**Comment by steebchen** [comment] 2023-06-16 19:49
Do you have rosetta enabled/installed? Because I'm also on M1 but I think it uses rosetta for me

**Comment by stillmatic** [comment] 2023-06-16 19:55
no, I don't use Rosetta, which would explain why it works in your case

I think https://github.com/steebchen/prisma-client-go/pull/874 should solve it, but let me test it real quick.

**Comment by steebchen** [comment] 2023-06-16 20:02
Thanks looks good, see my comment

**Comment by steebchen** [comment] 2023-06-16 20:26
dupe of #809

**Closed** 2023-06-18 00:31 UTC
